\restrict FiEgGGKv1qQ9hBU7ecb6S4mObm5IhqRyjBrjYfAcY7qaHLnEIK75cgpyQ4gHSsH
CREATE TABLE public.raw_vmware_host_hardware (
    data_type text NOT NULL,
    collection_timestamp timestamp with time zone NOT NULL,
    vcenter_uuid text NOT NULL,
    datacenter_moid text,
    cluster_moid text,
    host_moid text NOT NULL,
    vendor text,
    model text,
    uuid text,
    memory_size bigint,
    cpu_model text,
    cpu_mhz integer,
    num_cpu_pkgs integer,
    num_cpu_cores integer,
    num_cpu_threads integer,
    num_nics integer,
    num_hbas integer,
    system_info_vendor text,
    system_info_model text,
    system_info_uuid text,
    system_info_other_identifying_info text,
    product_name text,
    product_full_name text,
    product_vendor text,
    product_version text,
    product_build text,
    product_locale_version text,
    product_locale_build text,
    product_os_type text,
    product_product_line_id text,
    product_api_type text,
    product_api_version text,
    product_license_product_name text,
    product_license_product_version text
);
CREATE INDEX raw_vmware_host_hardware_collection_timestamp_idx ON public.raw_vmware_host_hardware USING btree (collection_timestamp DESC);
CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.raw_vmware_host_hardware FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker();
\unrestrict FiEgGGKv1qQ9hBU7ecb6S4mObm5IhqRyjBrjYfAcY7qaHLnEIK75cgpyQ4gHSsH
