---
- name: Datalake Collectors Senkronizasyonu
  hosts: all
  become: yes 

  vars:
    target_path: /Datalake_Project/
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  tasks:
    - name: GitHub collectors klasörünü sunucuya eşitle
      synchronize:
        src: ../../collectors/
        dest: "{{ target_path }}"
        archive: yes
        recursive: yes
        delete: no
        use_ssh_args: yes
        private_key: no
        rsync_path: "sudo rsync"
        rsync_opts:
          - "--checksum"
          - "--itemize-changes"
          - "--no-perms"
          - "--no-owner"
          - "--no-group"
          - "--exclude=configuration_file.json"
          - "--exclude=configuration_file.json.example"
          - "--exclude=.git"
          - "--exclude=.gitkeep"
      become: no
      register: rsync_result
      changed_when: rsync_result.stdout_lines | default([]) | length > 0
