---
# -----------------------------------------------------------------
# DC11 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC11 NiFi Guncellemesi
  hosts: NiFi_DC11
  become: yes
  tasks:
    - name: DC11 dosyalarini kopyala
      copy:
        src: ../files/dc11/
        dest: /opt/nifi/conf/
        owner: root  # <-- DÜZELTİLDİ (Eskisi: nifi)
        group: root  # <-- DÜZELTİLDİ (Eskisi: nifi)
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC12 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC12 NiFi Guncellemesi
  hosts: NiFi_DC12
  become: yes
  tasks:
    - name: DC12 dosyalarini kopyala
      copy:
        src: ../files/dc12/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC13 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC13 NiFi Guncellemesi
  hosts: NiFi_DC13
  become: yes
  tasks:
    - name: DC13 dosyalarini kopyala
      copy:
        src: ../files/dc13/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC14 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC14 NiFi Guncellemesi
  hosts: NiFi_DC14
  become: yes
  tasks:
    - name: DC14 dosyalarini kopyala
      copy:
        src: ../files/dc14/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC15 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC15 NiFi Guncellemesi
  hosts: NiFi_DC15
  become: yes
  tasks:
    - name: DC15 dosyalarini kopyala
      copy:
        src: ../files/dc15/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC16 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC16 NiFi Guncellemesi
  hosts: NiFi_DC16
  become: yes
  tasks:
    - name: DC16 dosyalarini kopyala
      copy:
        src: ../files/dc16/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC17 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC17 NiFi Guncellemesi
  hosts: NiFi_DC17
  become: yes
  tasks:
    - name: DC17 dosyalarini kopyala
      copy:
        src: ../files/dc17/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC-AZ11 (Azure) GÖREVLERİ
# -----------------------------------------------------------------
- name: DC-AZ11 NiFi Guncellemesi
  hosts: NiFi_DCAZ11
  become: yes
  tasks:
    - name: DCAZ11 dosyalarini kopyala
      copy:
        src: ../files/dcaz11/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted

# -----------------------------------------------------------------
# DC-ICT11 GÖREVLERİ
# -----------------------------------------------------------------
- name: DC-ICT11 NiFi Guncellemesi
  hosts: NiFi_DCICT11
  become: yes
  tasks:
    - name: DCICT11 dosyalarini kopyala
      copy:
        src: ../files/dcict11/
        dest: /opt/nifi/conf/
        owner: root
        group: root
        mode: '0640'
      notify: Restart NiFi

  handlers:
    - name: Restart NiFi
      service: name=nifi state=restarted