-- Generated by shared/service_mapping/generate_seed_sql.py
-- CRM GUI service mapping: pages registry + per-product seed + view + legacy drop
BEGIN;

DROP VIEW IF EXISTS v_gui_crm_product_mapping CASCADE;
DROP TABLE IF EXISTS gui_crm_service_mapping_seed CASCADE;
DROP TABLE IF EXISTS gui_crm_service_mapping_override CASCADE;
DROP TABLE IF EXISTS gui_crm_service_pages CASCADE;

CREATE TABLE gui_crm_service_pages (
    page_key          TEXT PRIMARY KEY,
    category_label    TEXT NOT NULL,
    gui_tab_binding   TEXT NOT NULL,
    resource_unit     TEXT NOT NULL DEFAULT 'Adet',
    icon              TEXT,
    route_hint        TEXT,
    tab_hint          TEXT,
    sub_tab_hint      TEXT
);

INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('backup_netbackup', 'NetBackup', 'backup.netbackup', 'GB');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('backup_veeam', 'Veeam backup', 'backup.veeam', 'per VM');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('backup_zerto', 'Zerto replication', 'backup.zerto', 'vCPU');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('database_managed', 'Managed database', 'data.database', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('dc_energy', 'Datacenter energy', 'datacenter.energy', 'kW');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('dc_hosting', 'Colocation / hosting', 'datacenter.hosting', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('firewall_citrix', 'Citrix ADC', 'security.firewall', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('firewall_fortigate', 'FortiGate', 'security.firewall', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('firewall_paloalto', 'Palo Alto', 'security.firewall', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('firewall_sophos', 'Sophos', 'security.firewall', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('licensing_microsoft', 'Microsoft CSP / M365', 'licensing.microsoft', 'per User');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('licensing_redhat', 'Red Hat', 'licensing.redhat', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('monitoring', 'Monitoring', 'operations.monitoring', 'per VM');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('other', 'Other / uncategorized', 'other', 'Adet');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('storage_s3', 'Object storage (S3)', 'storage.s3', 'GB');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('virt_classic', 'Classic virtualization', 'virtualization.classic', 'vCPU');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('virt_hyperconverged', 'Hyperconverged virtualization', 'virtualization.hyperconverged', 'vCPU');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('virt_nutanix', 'Pure Nutanix (AHV)', 'virtualization.nutanix', 'vCPU');
INSERT INTO gui_crm_service_pages (page_key, category_label, gui_tab_binding, resource_unit) VALUES ('virt_power', 'IBM Power LPAR', 'virtualization.power', 'core');

CREATE TABLE gui_crm_service_mapping_seed (
    productid   TEXT PRIMARY KEY,
    page_key    TEXT NOT NULL REFERENCES gui_crm_service_pages(page_key)
);

INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('5c613b12-100b-f111-8341-000d3a43e958', 'virt_nutanix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a44cb991-6b19-f111-8341-000d3a43e958', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a0463281-1e07-f111-8406-000d3a43e958', 'firewall_sophos');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0d88926d-1f07-f111-8406-000d3a43e958', 'firewall_sophos');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('302019d2-2007-f111-8406-000d3a43e958', 'firewall_sophos');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('2e7d742f-cd21-f111-88b3-000d3a43e958', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('fd05bfde-1434-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7403addf-1734-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7e5bd93b-3821-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a2e7d095-3821-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0d9c16df-3821-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('edb3353a-aae2-f011-8406-000d3a2b6ad9', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f99a8278-c3eb-f011-8406-000d3a2b6ad9', 'firewall_paloalto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7f26c99d-6b19-f111-8341-000d3a43e958', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ba2cca41-5207-f111-8406-000d3a43e958', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8222f1d3-cc21-f111-88b3-000d3a43e958', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d2635018-5c6d-f011-b4cc-6045bd93381c', 'backup_netbackup');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('791eb3bb-c6dc-f011-8406-000d3a2b6ad9', 'firewall_paloalto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('aa106751-1634-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6aae70ae-1634-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d5b17b5e-1734-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('fdd5eb96-1834-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('1af42000-1934-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f07e1687-8f94-f011-b41c-000d3a46c848', 'backup_zerto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('839b0f99-8bb9-f011-bbd3-000d3abf9410', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('3e920c3e-8cb9-f011-bbd3-000d3abf9410', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('aa5a139d-3721-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('473d0df2-3b21-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('208ab317-3e21-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a2625f6d-3e21-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('1c905109-46a8-f011-bbd2-00224884a075', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('79109ee8-47a8-f011-bbd2-00224884a075', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f6d0d00f-2495-f011-b41c-002248873b68', 'backup_zerto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('4979b8e9-2595-f011-b41c-002248873b68', 'backup_zerto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('b6f200b4-aae2-f011-8406-000d3a2b6ad9', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d6b3ff62-1934-f111-88b3-000d3a43e958', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('788421d5-8ab9-f011-bbd3-000d3abf9410', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('472258e9-3721-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d02c2e5a-2895-f011-b41c-002248873b68', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0669c1fe-d813-f111-8341-6045bd8e22e8', 'database_managed');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('09325140-e437-f111-88b3-6045bd8e2841', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6e625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('70625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('72625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('74625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('76625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('88625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8a625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('90625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('9a625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('bc625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0c635018-5c6d-f011-b4cc-6045bd93381c', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('1e635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('20635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('02462de7-3c21-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('da9d8144-3d21-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ea2a34b3-3d21-f111-88b3-0022487ff527', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ea0d4c73-47a8-f011-bbd2-00224884a075', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('accab11e-48a8-f011-bbd2-00224884a075', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('2f934c48-2795-f011-b41c-002248873b68', 'backup_zerto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d5f69091-2795-f011-b41c-002248873b68', 'backup_zerto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8a5a940d-2895-f011-b41c-002248873b68', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('19b2a1b5-2b21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('3826d816-2c21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8c66abd7-2e21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('4000e63e-2f21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('9de6f6a4-2f21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('e125d70e-3121-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c4482aed-3121-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ffb84ac0-3221-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('94493a76-0200-f111-8406-6045bd8e2841', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7a625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7e625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('82625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('84625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('9156fb9d-2895-f011-b41c-002248873b68', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('122834c9-2621-f111-88b3-6045bd8e210f', 'database_managed');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('cd5b77d6-2a21-f111-88b3-6045bd8e210f', 'database_managed');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('2d63dc54-2b21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c3f539a1-2c21-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c109fe7a-3121-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('4b26b520-3321-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8e625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('96625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('be625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c6625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ca625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('cc625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ce625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d0625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d2625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d8625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('da625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('dc625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('fc625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('12635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0caa430b-3421-f111-88b3-6045bd8e210f', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('9a8ef266-ca21-f111-88b3-6045bd8e22e8', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6c625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8c625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('92625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('94625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('98625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a8625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('aa625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ac625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ae625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('b0625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('b4625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('b8625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c0625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c2625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c4625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d6625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('de625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('00635018-5c6d-f011-b4cc-6045bd93381c', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('14635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('16635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('86625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('9c625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('9e625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a2625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a4625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a6625018-5c6d-f011-b4cc-6045bd93381c', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('b2625018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c8625018-5c6d-f011-b4cc-6045bd93381c', 'firewall_citrix');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('10635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('44635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('58635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('62635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('64635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('66635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('70635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7a635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ee635018-5c6d-f011-b4cc-6045bd93381c', 'dc_hosting');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c42840ff-86ad-f011-bbd3-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('e2f585bb-c2e0-f011-8406-6045bd9c244d', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('1c48fee3-a4a9-f011-bbd3-7c1e52724e0e', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('4fb6d8c3-eebe-f011-bbd3-7c1e52724e0e', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('18635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('2c635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('3c635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('3e635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7e635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('82635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('88635018-5c6d-f011-b4cc-6045bd93381c', 'virt_power');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('90635018-5c6d-f011-b4cc-6045bd93381c', 'virt_power');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d8635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('dc635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('e0635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('e4635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('fa635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('5d648615-50cf-f011-8544-6045bd9a4052', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('b68d6594-edbe-f011-bbd3-7c1e52724e0e', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a2e0a22c-efbe-f011-bbd3-7c1e52724e0e', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('1a635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('1c635018-5c6d-f011-b4cc-6045bd93381c', 'virt_hyperconverged');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('42635018-5c6d-f011-b4cc-6045bd93381c', 'storage_s3');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('56635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('5a635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('5e635018-5c6d-f011-b4cc-6045bd93381c', 'monitoring');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('72635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('74635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('76635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('78635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('7c635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('84635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8a635018-5c6d-f011-b4cc-6045bd93381c', 'virt_power');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c4635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c6635018-5c6d-f011-b4cc-6045bd93381c', 'monitoring');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ca635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('e2635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f8635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('219de50f-887f-f011-b4cc-6045bd9510fc', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('981b2033-cb21-f111-88b3-6045bd9a8d08', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('4f02c341-cc21-f111-88b3-6045bd9a8d08', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('24635018-5c6d-f011-b4cc-6045bd93381c', 'storage_s3');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('26635018-5c6d-f011-b4cc-6045bd93381c', 'storage_s3');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('2a635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('2e635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('30635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('36635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('38635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6a635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6c635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6e635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('80635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('86635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8c635018-5c6d-f011-b4cc-6045bd93381c', 'virt_power');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('cc635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('d6635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('de635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('bfdeb52b-edbe-f011-bbd3-7c1e52724e0e', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('80c902fe-edbe-f011-bbd3-7c1e52724e0e', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('68635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('3a50d543-79cf-f011-8544-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8770a225-94ad-f011-bbd3-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('8e635018-5c6d-f011-b4cc-6045bd93381c', 'virt_power');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('da635018-5c6d-f011-b4cc-6045bd93381c', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f6635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('6ab0bc7e-86ad-f011-bbd3-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0c7be560-88ad-f011-bbd3-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('048e2c67-bafa-f011-8406-7c1e52710895', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c87bff30-1dd0-f011-8544-7c1e52724e0e', 'backup_netbackup');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('45f2398d-efbe-f011-bbd3-7c1e52724e0e', 'firewall_fortigate');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('a6635018-5c6d-f011-b4cc-6045bd93381c', 'firewall_sophos');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ea635018-5c6d-f011-b4cc-6045bd93381c', 'dc_hosting');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f0635018-5c6d-f011-b4cc-6045bd93381c', 'dc_energy');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('69e3822e-6eaa-f011-bbd3-6045bd9a4052', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c03d5622-52cf-f011-8544-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('0e5185a0-79cf-f011-8544-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('35654556-87ad-f011-bbd3-6045bd9aea7b', 'licensing_microsoft');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f71160a5-b9fa-f011-8406-7c1e52710895', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('60d2f3d5-18d0-f011-8544-7c1e52724e0e', 'virt_classic');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('c8635018-5c6d-f011-b4cc-6045bd93381c', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('ec635018-5c6d-f011-b4cc-6045bd93381c', 'dc_hosting');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('fc635018-5c6d-f011-b4cc-6045bd93381c', 'backup_veeam');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('04645018-5c6d-f011-b4cc-6045bd93381c', 'backup_zerto');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('00712389-cb21-f111-88b3-6045bd9a8d08', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('f5abfcde-cb21-f111-88b3-6045bd9a8d08', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('512b6d09-dbfc-f011-8406-7c1e52710613', 'other');
INSERT INTO gui_crm_service_mapping_seed (productid, page_key) VALUES ('aad2f3d5-18d0-f011-8544-7c1e52724e0e', 'virt_classic');

CREATE TABLE gui_crm_service_mapping_override (
    productid    TEXT PRIMARY KEY,
    page_key     TEXT NOT NULL REFERENCES gui_crm_service_pages(page_key),
    notes        TEXT,
    updated_by   TEXT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

DO $migrate_manual$
BEGIN
  IF to_regclass('public.discovery_crm_product_category_alias') IS NOT NULL THEN
    INSERT INTO gui_crm_service_mapping_override (productid, page_key, notes, updated_by, updated_at)
    SELECT pca.productid,
           CASE WHEN pca.category_code IN (SELECT page_key FROM gui_crm_service_pages)
                THEN pca.category_code ELSE 'other' END,
           COALESCE(pca.notes, 'migrated from discovery_crm_product_category_alias'),
           'migration',
           now()
    FROM   discovery_crm_product_category_alias pca
    WHERE  pca.source = 'manual';
  END IF;
END $migrate_manual$;

CREATE OR REPLACE VIEW v_gui_crm_product_mapping AS
SELECT
    pr.productid,
    pr.name AS product_name,
    pr.productnumber AS product_number,
    COALESCE(o.page_key, s.page_key, 'other') AS category_code,
    pg.category_label,
    pg.gui_tab_binding,
    NULL::text AS resource_unit,
    CASE WHEN o.productid IS NOT NULL THEN 'override' WHEN s.productid IS NOT NULL THEN 'yaml' ELSE 'default' END AS mapping_source,
    COALESCE(NULLIF(TRIM(pg.resource_unit), ''), 'Adet') AS page_resource_unit
FROM   discovery_crm_products pr
LEFT JOIN gui_crm_service_mapping_seed s ON s.productid = pr.productid
LEFT JOIN gui_crm_service_mapping_override o ON o.productid = pr.productid
JOIN   gui_crm_service_pages pg ON pg.page_key = COALESCE(o.page_key, s.page_key, 'other');

DROP TABLE IF EXISTS discovery_crm_product_category_alias CASCADE;

COMMIT;
