\restrict 0x6dkejvenssAWvSZRKD05T1nW5KaCLxA5dUaFBbBcqYxjhgAIHrlYGdQhF3lDb
CREATE TABLE public.discovery_netbox_inventory_device (
    id bigint NOT NULL,
    data_type character varying(50),
    count bigint,
    url text,
    display text,
    name text,
    device_type_id bigint,
    device_type_url text,
    device_type_display text,
    device_type_name text,
    device_type_slug text,
    manufacturer_id bigint,
    manufacturer_url text,
    manufacturer_display text,
    manufacturer_name text,
    manufacturer_slug text,
    device_role_id bigint,
    device_role_url text,
    device_role_display text,
    device_role_name text,
    device_role_slug text,
    tenant_id bigint,
    platform_id bigint,
    platform_name text,
    serial text,
    asset_tag text,
    site_id bigint,
    site_url text,
    site_display text,
    site_name text,
    site_slug text,
    location_id bigint,
    location_url text,
    location_display text,
    location_name text,
    location_slug text,
    location_depth bigint,
    rack_id bigint,
    rack_url text,
    rack_display text,
    rack_name text,
    "position" numeric,
    face_value text,
    face_label text,
    latitude numeric,
    longitude numeric,
    parent_device_id bigint,
    status_value text,
    status_label text,
    airflow_value text,
    airflow_label text,
    primary_ip_id bigint,
    primary_ip_address text,
    description text,
    comments text,
    custom_fields jsonb,
    tags1_id bigint,
    tags1_url text,
    tags1_display text,
    tags1_name text,
    tags1_slug text,
    tags1_color text,
    tags2_id bigint,
    tags2_url text,
    tags2_display text,
    tags2_name text,
    tags2_slug text,
    tags2_color text,
    tags3_id bigint,
    tags3_url text,
    tags3_display text,
    tags3_name text,
    tags3_slug text,
    tags3_color text,
    tags4_id bigint,
    tags4_url text,
    tags4_display text,
    tags4_name text,
    tags4_slug text,
    tags4_color text,
    tags5_id bigint,
    tags5_url text,
    tags5_display text,
    tags5_name text,
    tags5_slug text,
    tags5_color text,
    created timestamp with time zone,
    last_updated timestamp with time zone,
    console_port_count bigint,
    console_server_port_count bigint,
    power_port_count bigint,
    power_outlet_count bigint,
    interface_count bigint,
    front_port_count bigint,
    rear_port_count bigint,
    device_bay_count bigint,
    module_bay_count bigint,
    inventory_item_count bigint,
    collection_time timestamp with time zone,
    cpu character varying(255),
    cvm_ip character varying(255),
    datalake_monitoring character varying(255),
    izlenmeli character varying(255),
    kurulum_tarihi character varying(255),
    sahiplik character varying(255),
    total_cores character varying(255),
    total_ram character varying(255),
    vmware_ip character varying(255),
    zabbix_monitoring character varying(255),
    tenant_name character varying(255)
);
ALTER TABLE ONLY public.discovery_netbox_inventory_device
    ADD CONSTRAINT discovery_netbox_inventory_device_pkey PRIMARY KEY (id);
CREATE INDEX idx_netbox_device_site_id ON public.discovery_netbox_inventory_device USING btree (site_id);
CREATE INDEX idx_netbox_device_tenant_id ON public.discovery_netbox_inventory_device USING btree (tenant_id);
\unrestrict 0x6dkejvenssAWvSZRKD05T1nW5KaCLxA5dUaFBbBcqYxjhgAIHrlYGdQhF3lDb
