\restrict dvel2p5SLqJq86do2zycxAdc2yjB1vsQQgfO1BMljsg8GZmD1lhD18PC2LstfV5
CREATE TABLE public.discovery_loki_location (
    id bigint NOT NULL,
    data_type character varying(50),
    url text,
    display text,
    name text,
    slug text,
    site_id bigint,
    site_url text,
    site_display text,
    site_name text,
    site_slug text,
    parent_id bigint,
    parent_url text,
    parent_display text,
    parent_name text,
    parent_slug text,
    status_value text,
    status_label text,
    tenant_id bigint,
    description text,
    tag1_id bigint,
    tag1_url text,
    tag1_display text,
    tag1_name text,
    tag1_slug text,
    tag1_color text,
    tag2_id bigint,
    tag2_url text,
    tag2_display text,
    tag2_name text,
    tag2_slug text,
    tag2_color text,
    tag3_id bigint,
    tag3_url text,
    tag3_display text,
    tag3_name text,
    tag3_slug text,
    tag3_color text,
    tag4_id bigint,
    tag4_url text,
    tag4_display text,
    tag4_name text,
    tag4_slug text,
    tag4_color text,
    tag5_id bigint,
    tag5_url text,
    tag5_display text,
    tag5_name text,
    tag5_slug text,
    tag5_color text,
    custom_fields jsonb,
    created character varying,
    last_updated character varying,
    rack_count bigint,
    device_count bigint,
    _depth bigint,
    collection_time character varying DEFAULT now()
);
ALTER TABLE ONLY public.discovery_loki_location
    ADD CONSTRAINT discovery_loki_location_pkey PRIMARY KEY (id);
\unrestrict dvel2p5SLqJq86do2zycxAdc2yjB1vsQQgfO1BMljsg8GZmD1lhD18PC2LstfV5
