\restrict z9KYUz3eaee4efLApcmykn91jrSYEpyB8VTwgiCTqmOVHhuIQzmKA2HAIPYCiMI
CREATE TABLE public.ibm_vios_general (
    vios_details_servername character varying(255),
    vios_details_viosname character varying(255),
    vios_details_viosid integer,
    vios_details_viosstate character varying(255),
    vios_details_affinityscore integer,
    vios_memory_servername character varying(255),
    vios_memory_viosname character varying(255),
    vios_memory_assignedmem double precision,
    vios_memory_utilizedmem double precision,
    vios_memory_virtualpersistentmem double precision,
    vios_processor_servername character varying(255),
    vios_processor_viosname character varying(255),
    vios_processor_poolid integer,
    vios_processor_weight integer,
    vios_processor_mode character varying(255),
    vios_processor_maxvirtualprocessors double precision,
    vios_processor_currentvirtualprocessors double precision,
    vios_processor_maxprocunits double precision,
    vios_processor_entitledprocunits double precision,
    vios_processor_utilizedprocunits double precision,
    vios_processor_utilizedprocunitsdeductidle double precision,
    vios_processor_utilizedcappedprocunits double precision,
    vios_processor_utilizeduncappedprocunits double precision,
    vios_processor_idleprocunits double precision,
    vios_processor_donatedprocunits double precision,
    vios_processor_timespentwaitingfordispatch double precision,
    vios_processor_timeperinstructionexecution double precision,
    vios_network_lpars_servername character varying(255),
    vios_network_lpars_viosname character varying(255),
    vios_network_lpars_clientlpars integer,
    vios_network_shared_servername character varying(255),
    vios_network_shared_viosname character varying(255),
    vios_network_shared_id character varying(255),
    vios_network_shared_location character varying(255),
    vios_network_shared_type character varying(255),
    vios_network_shared_physicallocation character varying(255),
    vios_network_shared_receivedpackets double precision,
    vios_network_shared_sentpackets double precision,
    vios_network_shared_droppedpackets double precision,
    vios_network_shared_sentbytes double precision,
    vios_network_shared_receivedbytes double precision,
    vios_network_shared_transferredbytes double precision,
    vios_storage_lpars_servername character varying(255),
    vios_storage_lpars_viosname character varying(255),
    vios_storage_lpars_clientlpars integer,
    servername character varying(255),
    viosname character varying(255),
    "time" timestamp with time zone NOT NULL
);
ALTER TABLE ONLY public.ibm_vios_general
    ADD CONSTRAINT ibm_vios_general_viosname_time_key UNIQUE (viosname, "time");
CREATE INDEX ibm_vios_general_time_idx ON public.ibm_vios_general USING btree ("time" DESC);
CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.ibm_vios_general FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker();
\unrestrict z9KYUz3eaee4efLApcmykn91jrSYEpyB8VTwgiCTqmOVHhuIQzmKA2HAIPYCiMI
