\restrict 3WMOPAtJ3rZlcpFFGhSy63PbEmwVBfY8YOyKxZTgWHTby3aCgcaifsvEZoRpdHu
CREATE TABLE public.ibm_lpar_general (
    lpar_details_servername character varying(255),
    lpar_details_lparname character varying(255),
    lpar_details_id integer,
    lpar_details_name character varying(255),
    lpar_details_state character varying(50),
    lpar_details_type character varying(50),
    lpar_details_ostype character varying(100),
    lpar_details_affinityscore integer,
    lpar_processor_servername character varying(255),
    lpar_processor_lparname character varying(255),
    lpar_processor_poolid integer,
    lpar_processor_weight integer,
    lpar_processor_mode character varying(50),
    lpar_processor_maxvirtualprocessors double precision,
    lpar_processor_currentvirtualprocessors double precision,
    lpar_processor_maxprocunits double precision,
    lpar_processor_entitledprocunits double precision,
    lpar_processor_utilizedprocunitsdeductidle double precision,
    lpar_processor_utilizedprocunits double precision,
    lpar_processor_utilizedcappedprocunits double precision,
    lpar_processor_utilizeduncappedprocunits double precision,
    lpar_processor_idleprocunits double precision,
    lpar_processor_donatedprocunits double precision,
    lpar_processor_timespentwaitingfordispatch double precision,
    lpar_processor_timeperinstructionexecution double precision,
    lpar_memory_servername character varying(255),
    lpar_memory_lparname character varying(255),
    lpar_memory_logicalmem double precision,
    lpar_memory_backedphysicalmem double precision,
    lpar_memory_virtualpersistentmem double precision,
    lpar_storage_virtual_servername character varying(255),
    lpar_storage_virtual_lparname character varying(255),
    lpar_storage_virtual_id character varying(255),
    lpar_storage_virtual_location character varying(255),
    lpar_storage_virtual_viosid integer,
    lpar_storage_virtual_type character varying(50),
    lpar_storage_virtual_physicallocation character varying(255),
    lpar_storage_virtual_numofreads double precision,
    lpar_storage_virtual_numofwrites double precision,
    lpar_storage_virtual_readbytes double precision,
    lpar_storage_virtual_writebytes double precision,
    servername character varying(255),
    lparname character varying(255),
    "time" timestamp with time zone NOT NULL
);
ALTER TABLE ONLY public.ibm_lpar_general
    ADD CONSTRAINT ibm_lpar_general_lparname_time_key UNIQUE (lparname, "time");
CREATE INDEX ibm_lpar_general_time_idx ON public.ibm_lpar_general USING btree ("time" DESC);
CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.ibm_lpar_general FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker();
\unrestrict 3WMOPAtJ3rZlcpFFGhSy63PbEmwVBfY8YOyKxZTgWHTby3aCgcaifsvEZoRpdHu
