\restrict PxJd1M5emZn8P6rnXHufV4c4iNAQiR061hiUeNm9Rq9XrXA4dkhZjsRx6rPdWyg
CREATE TABLE public.loki_device_types (
    id bigint NOT NULL,
    url character varying(2048),
    display_url character varying(2048),
    display character varying(255),
    manufacturer_id bigint,
    manufacturer_url character varying(2048),
    manufacturer_display character varying(255),
    manufacturer_name character varying(255),
    manufacturer_slug character varying(100),
    default_platform_id bigint,
    default_platform_url character varying(2048),
    default_platform_display character varying(255),
    default_platform_name character varying(255),
    model character varying(255),
    slug character varying(100),
    part_number character varying(255),
    u_height double precision,
    exclude_from_utilization boolean,
    is_full_depth boolean,
    subdevice_role character varying(255),
    airflow character varying(255),
    weight double precision,
    weight_unit character varying(255),
    front_image character varying(2048),
    rear_image character varying(2048),
    description character varying(500),
    comments character varying(500),
    tags jsonb,
    custom_fields jsonb,
    created timestamp with time zone,
    last_updated timestamp with time zone,
    device_count integer,
    console_port_template_count integer,
    console_server_port_template_count integer,
    power_port_template_count integer,
    power_outlet_template_count integer,
    interface_template_count integer,
    front_port_template_count integer,
    rear_port_template_count integer,
    device_bay_template_count integer,
    module_bay_template_count integer,
    inventory_item_template_count integer
);
CREATE UNIQUE INDEX ux_loki_device_types_id ON public.loki_device_types USING btree (id);
\unrestrict PxJd1M5emZn8P6rnXHufV4c4iNAQiR061hiUeNm9Rq9XrXA4dkhZjsRx6rPdWyg
