\restrict hU8HdBIU3gGEpjVBUzpTANZtg0DcDUDCnNjeQhGafcUBry9H73eVtJDMJyUTwYt
CREATE TABLE public.loki_locations (
    id integer,
    url character varying(255),
    display character varying(255),
    name character varying(255),
    slug character varying(255),
    site_id integer,
    site_url character varying(255),
    site_display character varying(255),
    site_name character varying(255),
    site_slug character varying(255),
    parent_id integer,
    parent_url character varying(255),
    parent_display character varying(255),
    parent_name character varying(255),
    parent_slug character varying(255),
    status_value character varying(255),
    status_label character varying(255),
    tenant_id integer,
    description character varying(255),
    tag1_id integer,
    tag1_url character varying(255),
    tag1_display character varying(255),
    tag1_name character varying(255),
    tag1_slug character varying(255),
    tag1_color character varying(255),
    tag2_id integer,
    tag2_url character varying(255),
    tag2_display character varying(255),
    tag2_name character varying(255),
    tag2_slug character varying(255),
    tag2_color character varying(255),
    tag3_id integer,
    tag3_url character varying(255),
    tag3_display character varying(255),
    tag3_name character varying(255),
    tag3_slug character varying(255),
    tag3_color character varying(255),
    tag4_id integer,
    tag4_url character varying(255),
    tag4_display character varying(255),
    tag4_name character varying(255),
    tag4_slug character varying(255),
    tag4_color character varying(255),
    tag5_id integer,
    tag5_url character varying(255),
    tag5_display character varying(255),
    tag5_name character varying(255),
    tag5_slug character varying(255),
    tag5_color character varying(255),
    custom_fields text,
    created timestamp without time zone,
    last_updated timestamp without time zone,
    rack_count integer,
    device_count integer,
    _depth integer,
    collection_time timestamp without time zone DEFAULT now()
);
CREATE INDEX idx_loki_locations_name ON public.loki_locations USING btree (name);
CREATE INDEX idx_loki_locations_parent_name ON public.loki_locations USING btree (parent_name);
\unrestrict hU8HdBIU3gGEpjVBUzpTANZtg0DcDUDCnNjeQhGafcUBry9H73eVtJDMJyUTwYt
