\restrict NGf0q8lNgexRzhSBvGlXdl9DbT79DhYh7eEq0uzPTrvSvnBMbrNOldhpmWct8Eq
CREATE TABLE public.loki_racks (
    id integer,
    url character varying(255),
    display character varying(255),
    name character varying(255),
    facility_id integer,
    site_id integer,
    site_url character varying(255),
    site_display character varying(255),
    site_name character varying(255),
    site_slug character varying(255),
    location_id integer,
    location_url character varying(255),
    location_display character varying(255),
    location_name character varying(255),
    location_slug character varying(255),
    location_depth integer,
    tenant character varying,
    status_value character varying(255),
    status_label character varying(255),
    role_id integer,
    role_url character varying(255),
    role_display character varying(255),
    role_name character varying(255),
    role_slug character varying(255),
    serial character varying(255),
    asset_tag character varying(255),
    type character varying(255),
    width_value integer,
    width_label character varying(255),
    u_height integer,
    starting_unit integer,
    weight integer,
    max_weight integer,
    weight_unit character varying(255),
    desc_units boolean,
    outer_width integer,
    outer_depth integer,
    outer_unit_value character varying(255),
    outer_unit_label character varying(255),
    mounting_depth integer,
    description character varying,
    comments character varying,
    tag1_id integer,
    tag1_url character varying(255),
    tag1_display character varying(255),
    tag1_name character varying(255),
    tag1_slug character varying(255),
    tag1_color character varying(255),
    tag2_id integer,
    tag2_url character varying(255),
    tag2_display character varying(255),
    tag2_name character varying(255),
    tag2_slug character varying(255),
    tag2_color character varying(255),
    tag3_id integer,
    tag3_url character varying(255),
    tag3_display character varying(255),
    tag3_name character varying(255),
    tag3_slug character varying(255),
    tag3_color character varying(255),
    tag4_id integer,
    tag4_url character varying(255),
    tag4_display character varying(255),
    tag4_name character varying(255),
    tag4_slug character varying(255),
    tag4_color character varying(255),
    tag5_id integer,
    tag5_url character varying(255),
    tag5_display character varying(255),
    tag5_name character varying(255),
    tag5_slug character varying(255),
    tag5_color character varying(255),
    kabin_enerji character varying(255),
    kabin_pdu_a_ip character varying(255),
    kabin_pdu_b_ip character varying(255),
    created timestamp without time zone,
    last_updated timestamp without time zone,
    device_count integer,
    powerfeed_count integer,
    collection_time timestamp without time zone DEFAULT now()
);
CREATE INDEX idx_loki_racks_collection_time ON public.loki_racks USING btree (collection_time);
CREATE INDEX idx_loki_racks_id ON public.loki_racks USING btree (id);
CREATE INDEX idx_loki_racks_kabin_enerji ON public.loki_racks USING btree (kabin_enerji);
CREATE INDEX idx_loki_racks_location_name ON public.loki_racks USING btree (location_name);
\unrestrict NGf0q8lNgexRzhSBvGlXdl9DbT79DhYh7eEq0uzPTrvSvnBMbrNOldhpmWct8Eq
