\restrict KCiGDL4dYWKi8XLKv4OyehsviGQIwEXIJlpMD7WsEkmwgBBuqfI41dyVZkzOeh0
CREATE TABLE public.loki_devices (
    id integer,
    url character varying(255),
    display character varying(255),
    name character varying(255),
    device_type_id integer,
    device_type_url character varying(255),
    device_type_display character varying(255),
    device_type_name character varying(255),
    device_type_slug character varying(255),
    manufacturer_id integer,
    manufacturer_url character varying(255),
    manufacturer_display character varying(255),
    manufacturer_name character varying(255),
    manufacturer_slug character varying(255),
    device_role_id integer,
    device_role_url character varying(255),
    device_role_display character varying(255),
    device_role_name character varying(255),
    device_role_slug character varying(255),
    tenant_id integer,
    platform_id integer,
    platform_name character varying(255),
    serial character varying(255),
    asset_tag character varying(255),
    site_id integer,
    site_url character varying(255),
    site_display character varying(255),
    site_name character varying(255),
    site_slug character varying(255),
    location_id integer,
    location_url character varying(255),
    location_display character varying(255),
    location_name character varying(255),
    location_slug character varying(255),
    location_depth integer,
    rack_id integer,
    rack_url character varying(255),
    rack_display character varying(255),
    rack_name character varying(255),
    "position" numeric,
    face_value character varying(255),
    face_label character varying(255),
    latitude numeric,
    longitude numeric,
    parent_device_id integer,
    status_value character varying(255),
    status_label character varying(255),
    airflow_value character varying(255),
    airflow_label character varying(255),
    primary_ip_id integer,
    primary_ip_address character varying(255),
    description character varying(30000),
    comments character varying(30000),
    tag1_id integer,
    tag1_url character varying(255),
    tag1_display character varying(255),
    tag1_name character varying(255),
    tag1_slug character varying(255),
    tag1_color character varying(255),
    tag2_id integer,
    tag2_url character varying(255),
    tag2_display character varying(255),
    tag2_name character varying(255),
    tag2_slug character varying(255),
    tag2_color character varying(255),
    tag3_id integer,
    tag3_url character varying(255),
    tag3_display character varying(255),
    tag3_name character varying(255),
    tag3_slug character varying(255),
    tag3_color character varying(255),
    tag4_id integer,
    tag4_url character varying(255),
    tag4_display character varying(255),
    tag4_name character varying(255),
    tag4_slug character varying(255),
    tag4_color character varying(255),
    tag5_id integer,
    tag5_url character varying(255),
    tag5_display character varying(255),
    tag5_name character varying(255),
    tag5_slug character varying(255),
    tag5_color character varying(255),
    custom_fields text,
    created timestamp without time zone,
    last_updated timestamp without time zone,
    console_port_count integer,
    console_server_port_count integer,
    power_port_count integer,
    power_outlet_count integer,
    interface_count integer,
    front_port_count integer,
    rear_port_count integer,
    device_bay_count integer,
    module_bay_count integer,
    inventory_item_count integer,
    collection_time timestamp without time zone DEFAULT now()
);
CREATE INDEX idx_loki_devices_name ON public.loki_devices USING btree (name);
CREATE INDEX idx_loki_devices_rack_id ON public.loki_devices USING btree (rack_id);
\unrestrict KCiGDL4dYWKi8XLKv4OyehsviGQIwEXIJlpMD7WsEkmwgBBuqfI41dyVZkzOeh0
