\restrict rTZIZmVYjxu5errVNgnqEPwxXt48rFPHiEpaxnv3OZyUR4suhEHg2Y2iEEaOcAY
CREATE TABLE public.raw_netbackup_jobs_metrics (
    data_type character varying(50) NOT NULL,
    collection_timestamp timestamp with time zone NOT NULL,
    netbackup_host character varying(50) DEFAULT ''::character varying NOT NULL,
    id character varying(255) NOT NULL,
    type character varying(50),
    jobid character varying(255),
    parentjobid character varying(255),
    activeprocessid character varying(255),
    jobtype character varying(100),
    jobsubtype character varying(100),
    policytype character varying(100),
    policyname character varying(255),
    scheduletype character varying(100),
    schedulename character varying(255),
    clientname character varying(255),
    jobowner character varying(255),
    jobgroup character varying(255),
    backupid character varying(255),
    destinationstorageunitname character varying(255),
    destinationmediaservername character varying(255),
    datamovement character varying(100),
    streamnumber integer,
    copynumber integer,
    priority integer,
    compression integer,
    state character varying(100),
    numberoffiles bigint,
    estimatedfiles bigint,
    kilobytestransferred bigint,
    kilobytestotransfer bigint,
    transferrate numeric(10,2),
    percentcomplete numeric(5,2),
    restartable boolean,
    suspendable boolean,
    resumable boolean,
    frozenimage boolean,
    transporttype character varying(100),
    currentoperation integer,
    sessionid character varying(255),
    numberoftapetoeject integer,
    submissiontype integer,
    auditdomaintype integer,
    starttime timestamp with time zone,
    endtime timestamp with time zone,
    activetrystarttime timestamp with time zone,
    lastupdatetime timestamp with time zone,
    childcount integer,
    jobpath character varying(500),
    retentionlevel integer,
    try integer,
    cancellable boolean,
    jobqueuereason integer,
    kilobytesdatatransferred bigint,
    elapsedtime character varying(50),
    activeelapsedtime character varying(50),
    dtemode character varying(100),
    workloaddisplayname character varying(255),
    offhosttype character varying(100),
    dedupratio numeric(5,2),
    status integer,
    profilename character varying(255),
    dedupspaceratio numeric(5,2),
    compressionspaceratio numeric(5,2)
);
ALTER TABLE ONLY public.raw_netbackup_jobs_metrics
    ADD CONSTRAINT raw_netbackup_jobs_metrics_pkey PRIMARY KEY (id, collection_timestamp);
CREATE INDEX raw_netbackup_jobs_metrics_clientname_idx ON public.raw_netbackup_jobs_metrics USING btree (clientname);
CREATE INDEX raw_netbackup_jobs_metrics_collection_timestamp_idx ON public.raw_netbackup_jobs_metrics USING btree (collection_timestamp DESC);
CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.raw_netbackup_jobs_metrics FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker();
\unrestrict rTZIZmVYjxu5errVNgnqEPwxXt48rFPHiEpaxnv3OZyUR4suhEHg2Y2iEEaOcAY
