\restrict CsyBIBDpQ7igUmv4jfuGbLln1Z4mGRvXCoWRblUWj2BA4ie32TZN7kH7pLqrMI8
CREATE TABLE public.raw_ibm_storage_ports (
    port_id character varying,
    type character varying,
    type_id integer,
    wwpn character varying,
    fc_wwpn character varying,
    fcoe_wwpn character varying,
    sas_wwn character varying,
    iqn character varying,
    hbt bigint,
    hbr bigint,
    het bigint,
    her bigint,
    cbt bigint,
    cbr bigint,
    cet bigint,
    cer bigint,
    lnbt bigint,
    lnbr bigint,
    lnet bigint,
    lner bigint,
    rmbt bigint,
    rmbr bigint,
    rmet bigint,
    rmer bigint,
    dtdt bigint,
    dtdc bigint,
    dtdm bigint,
    dtdt2 bigint,
    dtdc2 bigint,
    lf integer,
    lsy integer,
    lsi integer,
    pspe integer,
    itw integer,
    icrc integer,
    bbcz integer,
    tmp integer,
    tmpht integer,
    txpwr integer,
    txpwrlt integer,
    rxpwr integer,
    rxpwrlt integer,
    hsr integer,
    hsw integer,
    har integer,
    haw integer,
    "timestamp" timestamp without time zone DEFAULT now()
);
\unrestrict CsyBIBDpQ7igUmv4jfuGbLln1Z4mGRvXCoWRblUWj2BA4ie32TZN7kH7pLqrMI8
