\restrict 2oYGhsnTEEYbg47UXiRoe8baAVQdRPFiy4o2vswHnYFF3NE7V72whCW7qCGHqbx
CREATE TABLE public.raw_ibm_storage_mdiskgrp (
    id character varying(255),
    name character varying(255),
    status character varying(50),
    mdisk_count integer,
    vdisk_count integer,
    capacity character varying(50),
    extent_size integer,
    free_capacity character varying(50),
    virtual_capacity character varying(50),
    used_capacity character varying(50),
    real_capacity character varying(50),
    overallocation integer,
    warning integer,
    easy_tier character varying(50),
    easy_tier_status character varying(50),
    compression_active character varying(10),
    compression_virtual_capacity character varying(50),
    compression_compressed_capacity character varying(50),
    compression_uncompressed_capacity character varying(50),
    parent_mdisk_grp_id character varying(255),
    parent_mdisk_grp_name character varying(255),
    child_mdisk_grp_count integer,
    child_mdisk_grp_capacity character varying(50),
    type character varying(50),
    encrypt character varying(10),
    owner_type character varying(50),
    owner_id character varying(255),
    owner_name character varying(255),
    site_id integer,
    site_name character varying(255),
    data_reduction character varying(10),
    used_capacity_before_reduction character varying(50),
    used_capacity_after_reduction character varying(50),
    overhead_capacity character varying(50),
    deduplication_capacity_saving character varying(50),
    reclaimable_capacity character varying(50),
    easy_tier_fcm_over_allocation_max character varying(10),
    provisioning_policy_id character varying(255),
    provisioning_policy_name character varying(255),
    "timestamp" timestamp without time zone,
    storage_ip character varying(255)
);
\unrestrict 2oYGhsnTEEYbg47UXiRoe8baAVQdRPFiy4o2vswHnYFF3NE7V72whCW7qCGHqbx
