\restrict 9tkP8e5lKbZmKLcz9hVy0uUi2uLgRfMm2iEViFJEWOX32nZrSUHNCTHLFPGgmk3
CREATE TABLE public.raw_vmware_vm_runtime (
    data_type text NOT NULL,
    collection_timestamp timestamp with time zone NOT NULL,
    vcenter_uuid text NOT NULL,
    vm_moid text NOT NULL,
    power_state text,
    connection_state text,
    boot_time timestamp with time zone,
    suspend_time timestamp with time zone,
    suspend_interval bigint,
    question text,
    memory_overhead bigint,
    max_cpu_usage integer,
    max_memory_usage integer,
    num_mks_connections integer,
    record_replay_state text,
    clean_power_off boolean,
    need_secondary_reason text,
    online_standby boolean,
    min_required_evc_mode_key text,
    consolidation_needed boolean,
    offline_feature_requirement text,
    feature_requirement text,
    guest_tools_status text,
    guest_tools_version text,
    guest_tools_version_status text,
    guest_tools_running_status text,
    guest_tools_version_status2 text,
    guest_guest_id text,
    guest_guest_family text,
    guest_guest_full_name text,
    guest_host_name text,
    guest_ip_address text,
    guest_guest_state text,
    quick_stats_overall_cpu_usage integer,
    quick_stats_overall_cpu_demand integer,
    quick_stats_guest_memory_usage integer,
    quick_stats_host_memory_usage integer,
    quick_stats_guest_heartbeat_status text,
    quick_stats_distributed_cpu_entitlement integer,
    quick_stats_distributed_memory_entitlement integer,
    quick_stats_static_cpu_entitlement integer,
    quick_stats_static_memory_entitlement integer,
    quick_stats_private_memory integer,
    quick_stats_shared_memory integer,
    quick_stats_swapped_memory integer,
    quick_stats_ballooned_memory integer,
    quick_stats_consumed_overhead_memory integer,
    quick_stats_ft_log_bandwidth integer,
    quick_stats_ft_secondary_latency integer,
    quick_stats_ft_latency_status text,
    quick_stats_compressed_memory bigint,
    quick_stats_uptime_seconds bigint,
    quick_stats_ssd_swapped_memory bigint
);
CREATE INDEX raw_vmware_vm_runtime_collection_timestamp_idx ON public.raw_vmware_vm_runtime USING btree (collection_timestamp DESC);
CREATE TRIGGER ts_insert_blocker BEFORE INSERT ON public.raw_vmware_vm_runtime FOR EACH ROW EXECUTE FUNCTION _timescaledb_functions.insert_blocker();
\unrestrict 9tkP8e5lKbZmKLcz9hVy0uUi2uLgRfMm2iEViFJEWOX32nZrSUHNCTHLFPGgmk3
