\restrict nt2ha9MgHkxPWVgHxnrrXT0rJSm9iXee4V0luEukq22scClSaTdNd5qNG6OFGQP
CREATE TABLE public.raw_ibm_storage_system_stats (
    compression_cpu_pc double precision,
    cpu_pc double precision,
    fc_mb double precision,
    fc_io double precision,
    sas_mb double precision,
    sas_io double precision,
    iscsi_mb double precision,
    iscsi_io double precision,
    write_cache_pc double precision,
    total_cache_pc double precision,
    vdisk_mb double precision,
    vdisk_io double precision,
    vdisk_ms double precision,
    mdisk_mb double precision,
    mdisk_io double precision,
    mdisk_ms double precision,
    drive_mb double precision,
    drive_io double precision,
    drive_ms double precision,
    vdisk_r_mb double precision,
    vdisk_r_io double precision,
    vdisk_r_ms double precision,
    vdisk_w_mb double precision,
    vdisk_w_io double precision,
    vdisk_w_ms double precision,
    mdisk_r_mb double precision,
    mdisk_r_io double precision,
    mdisk_r_ms double precision,
    mdisk_w_mb double precision,
    mdisk_w_io double precision,
    mdisk_w_ms double precision,
    drive_r_mb double precision,
    drive_r_io double precision,
    drive_r_ms double precision,
    drive_w_mb double precision,
    drive_w_io double precision,
    drive_w_ms double precision,
    power_w double precision,
    temp_c double precision,
    temp_f double precision,
    iplink_mb double precision,
    iplink_io double precision,
    iplink_comp_mb double precision,
    cloud_up_mb double precision,
    cloud_up_ms double precision,
    cloud_down_mb double precision,
    cloud_down_ms double precision,
    iser_mb double precision,
    iser_io double precision,
    "timestamp" timestamp without time zone DEFAULT now(),
    storage_ip character varying(255)
);
\unrestrict nt2ha9MgHkxPWVgHxnrrXT0rJSm9iXee4V0luEukq22scClSaTdNd5qNG6OFGQP
