\restrict dS9gmqD6FpzGqW5obJd8VGb3l2IWUwphE7jDdhKzLq34pEqVnwaBCbVL8ulr5ZO
CREATE TABLE public.raw_ibm_storage_node_stats (
    node_id integer,
    node_name character varying(255),
    compression_cpu_pc integer,
    cpu_pc integer,
    fc_mb integer,
    fc_io integer,
    sas_mb integer,
    sas_io integer,
    iscsi_mb integer,
    iscsi_io integer,
    write_cache_pc integer,
    total_cache_pc integer,
    vdisk_mb integer,
    vdisk_io integer,
    vdisk_ms double precision,
    mdisk_mb integer,
    mdisk_io integer,
    mdisk_ms double precision,
    drive_mb integer,
    drive_io integer,
    drive_ms double precision,
    vdisk_r_mb integer,
    vdisk_r_io integer,
    vdisk_r_ms double precision,
    vdisk_w_mb integer,
    vdisk_w_io integer,
    vdisk_w_ms double precision,
    mdisk_r_mb integer,
    mdisk_r_io integer,
    mdisk_r_ms double precision,
    mdisk_w_mb integer,
    mdisk_w_io integer,
    mdisk_w_ms double precision,
    drive_r_mb integer,
    drive_r_io integer,
    drive_r_ms double precision,
    drive_w_mb integer,
    drive_w_io integer,
    drive_w_ms double precision,
    iplink_mb integer,
    iplink_io integer,
    iplink_comp_mb integer,
    cloud_up_mb integer,
    cloud_up_ms double precision,
    cloud_down_mb integer,
    cloud_down_ms double precision,
    iser_mb integer,
    iser_io integer,
    "timestamp" timestamp without time zone,
    storage_ip character varying(255)
);
\unrestrict dS9gmqD6FpzGqW5obJd8VGb3l2IWUwphE7jDdhKzLq34pEqVnwaBCbVL8ulr5ZO
