\restrict QX6py8S7GcO9lLxUEVn2aRRVaCPVuMszoQfzAMYhxP7RWwdkBaDS5bpOK0mtIjV
CREATE TABLE public.raw_ibm_storage_system (
    id character varying(255),
    name character varying(255),
    location character varying(255),
    partnership character varying(255),
    total_mdisk_capacity character varying(50),
    space_in_mdisk_grps character varying(50),
    space_allocated_to_vdisks character varying(50),
    total_free_space character varying(50),
    total_vdiskcopy_capacity character varying(50),
    total_used_capacity character varying(50),
    total_overallocation integer,
    total_vdisk_capacity character varying(50),
    total_allocated_extent_capacity character varying(50),
    statistics_status character varying(50),
    statistics_frequency character varying(50),
    cluster_locale character varying(50),
    time_zone character varying(100),
    code_level character varying(255),
    console_ip character varying(50),
    id_alias character varying(255),
    gm_link_tolerance integer,
    gm_inter_cluster_delay_simulation integer,
    gm_intra_cluster_delay_simulation integer,
    gm_max_host_delay integer,
    email_reply character varying(255),
    email_contact character varying(255),
    email_contact_primary character varying(255),
    email_contact_alternate character varying(255),
    email_contact_location character varying(255),
    email_contact2 character varying(255),
    email_contact2_primary character varying(255),
    email_contact2_alternate character varying(255),
    email_state character varying(50),
    inventory_mail_interval integer,
    cluster_ntp_ip_address character varying(255),
    cluster_isns_ip_address character varying(255),
    iscsi_auth_method character varying(50),
    iscsi_chap_secret character varying(255),
    auth_service_configured character varying(10),
    auth_service_enabled character varying(10),
    auth_service_url character varying(255),
    auth_service_user_name character varying(255),
    auth_service_pwd_set character varying(10),
    auth_service_cert_set character varying(10),
    auth_service_type character varying(50),
    relationship_bandwidth_limit integer,
    tiers_tier character varying(50),
    tiers_tier_capacity character varying(50),
    tiers_tier_free_capacity character varying(50),
    easy_tier_acceleration character varying(10),
    has_nas_key character varying(10),
    layer character varying(50),
    rc_buffer_size integer,
    compression_active character varying(10),
    compression_virtual_capacity character varying(50),
    compression_compressed_capacity character varying(50),
    compression_uncompressed_capacity character varying(50),
    cache_prefetch character varying(10),
    email_organization character varying(255),
    email_machine_address character varying(255),
    email_machine_city character varying(255),
    email_machine_state character varying(50),
    email_machine_zip character varying(50),
    email_machine_country character varying(50),
    total_drive_raw_capacity character varying(50),
    compression_destage_mode character varying(10),
    local_fc_port_mask character varying(255),
    partner_fc_port_mask character varying(255),
    high_temp_mode character varying(10),
    topology character varying(50),
    topology_status character varying(50),
    rc_auth_method character varying(50),
    vdisk_protection_time integer,
    vdisk_protection_enabled character varying(10),
    product_name character varying(255),
    odx character varying(10),
    max_replication_delay integer,
    partnership_exclusion_threshold integer,
    gen1_compatibility_mode_enabled character varying(10),
    ibm_customer character varying(255),
    ibm_component character varying(255),
    ibm_country character varying(255),
    tier_scm_compressed_data_used character varying(50),
    tier0_flash_compressed_data_used character varying(50),
    tier1_flash_compressed_data_used character varying(50),
    tier_enterprise_compressed_data_used character varying(50),
    tier_nearline_compressed_data_used character varying(50),
    total_reclaimable_capacity character varying(50),
    physical_capacity character varying(50),
    physical_free_capacity character varying(50),
    used_capacity_before_reduction character varying(50),
    used_capacity_after_reduction character varying(50),
    overhead_capacity character varying(50),
    deduplication_capacity_saving character varying(50),
    enhanced_callhome character varying(10),
    censor_callhome character varying(10),
    host_unmap character varying(10),
    backend_unmap character varying(10),
    quorum_mode character varying(50),
    quorum_site_id character varying(255),
    quorum_site_name character varying(255),
    quorum_lease character varying(50),
    automatic_vdisk_analysis_enabled character varying(10),
    callhome_accepted_usage character varying(10),
    safeguarded_copy_suspended character varying(10),
    "timestamp" timestamp without time zone,
    storage_ip character varying(255)
);
\unrestrict QX6py8S7GcO9lLxUEVn2aRRVaCPVuMszoQfzAMYhxP7RWwdkBaDS5bpOK0mtIjV
