\restrict 0fDO1WBtIFqkBwhmlpume8JtmHXqhykEbajLaov9xpiXVk8AdUUjJMQ5BWdIZ0f
CREATE TABLE public.raw_ibm_storage_mdisk_by_id (
    id integer,
    name character varying(255),
    status character varying(50),
    mdisk_count integer,
    vdisk_count integer,
    capacity character varying(50),
    extent_size integer,
    free_capacity character varying(50),
    virtual_capacity character varying(50),
    used_capacity character varying(50),
    real_capacity character varying(50),
    overallocation integer,
    warning integer,
    easy_tier character varying(50),
    easy_tier_status character varying(50),
    tiers_tier character varying(50),
    tiers_tier_mdisk_count integer,
    tiers_tier_capacity character varying(50),
    tiers_tier_free_capacity character varying(50),
    compression_active character varying(10),
    compression_virtual_capacity character varying(50),
    compression_compressed_capacity character varying(50),
    compression_uncompressed_capacity character varying(50),
    site_id integer,
    site_name character varying(50),
    parent_mdisk_grp_id integer,
    parent_mdisk_grp_name character varying(50),
    child_mdisk_grp_count integer,
    child_mdisk_grp_capacity character varying(50),
    type character varying(50),
    encrypt character varying(10),
    owner_type character varying(50),
    owner_id character varying(50),
    owner_name character varying(50),
    data_reduction character varying(10),
    used_capacity_before_reduction character varying(50),
    used_capacity_after_reduction character varying(50),
    overhead_capacity character varying(50),
    deduplication_capacity_saving character varying(50),
    reclaimable_capacity character varying(50),
    physical_capacity character varying(50),
    physical_free_capacity character varying(50),
    shared_resources character varying(50),
    vdisk_protection_enabled character varying(10),
    vdisk_protection_status character varying(50),
    easy_tier_fcm_over_allocation_max character varying(50),
    auto_expand character varying(10),
    auto_expand_max_capacity character varying(50),
    safeguarded character varying(10),
    provisioning_policy_id character varying(50),
    provisioning_policy_name character varying(50),
    "timestamp" timestamp without time zone,
    storage_ip character varying(255)
);
\unrestrict 0fDO1WBtIFqkBwhmlpume8JtmHXqhykEbajLaov9xpiXVk8AdUUjJMQ5BWdIZ0f
