CREATE TABLE public.nutanix_cluster_metrics (
	datacenter_name varchar(255) NOT NULL,
	cluster_name varchar(255) NOT NULL,
	cluster_uuid varchar(255) NOT NULL,
	num_nodes int4 NOT NULL,
	total_memory_capacity int8 NOT NULL,
	total_cpu_capacity int8 NOT NULL,
	total_vms int4 NOT NULL,
	network_transmitted_avg int8 NULL,
	network_received_avg int8 NULL,
	storage_capacity int8 NULL,
	storage_usage int8 NULL,
	memory_usage_min int8 NULL,
	memory_usage_max int8 NULL,
	memory_usage_avg int8 NULL,
	cpu_usage_min int8 NULL,
	cpu_usage_max int8 NULL,
	cpu_usage_avg int8 NULL,
	read_io_bandwidth_min int8 NULL,
	read_io_bandwidth_max int8 NULL,
	read_io_bandwidth_avg int8 NULL,
	write_io_bandwidth_min int8 NULL,
	write_io_bandwidth_max int8 NULL,
	write_io_bandwidth_avg int8 NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL
);


CREATE TABLE public.nutanix_host_metrics (
	id serial4 NOT NULL,
	host_name varchar(255) NOT NULL,
	host_uuid varchar(255) NOT NULL,
	cluster_uuid varchar(255) NOT NULL,
	total_memory_capacity int8 NOT NULL,
	total_cpu_capacity int8 NOT NULL,
	num_cpu_cores int4 NOT NULL,
	total_vms int4 NOT NULL,
	network_transmitted_avg int8 NULL,
	network_received_avg int8 NULL,
	memory_usage_min int8 NULL,
	memory_usage_max int8 NULL,
	memory_usage_avg int8 NULL,
	cpu_usage_min int8 NULL,
	cpu_usage_max int8 NULL,
	cpu_usage_avg int8 NULL,
	storage_capacity int8 NOT NULL,
	storage_usage int8 NOT NULL,
	read_io_bandwidth_min int8 NULL,
	read_io_bandwidth_max int8 NULL,
	read_io_bandwidth_avg int8 NULL,
	write_io_bandwidth_min int8 NULL,
	write_io_bandwidth_max int8 NULL,
	write_io_bandwidth_avg int8 NULL,
	collectiontime timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	boottime int8 NULL,
	CONSTRAINT nutanix_host_metrics_pkey PRIMARY KEY (id)
);


CREATE TABLE public.nutanix_vm_metrics (
	vm_name varchar(255) NOT NULL,
	vm_uuid uuid NOT NULL,
	cluster_uuid uuid NOT NULL,
	host_name varchar(255) NOT NULL,
	host_uuid uuid NOT NULL,
	power_state varchar(10) NOT NULL,
	memory_capacity int8 NULL,
	cpu_count int4 NULL,
	disk_capacity int8 NULL,
	hypervisor_read_io_bandwidth_min int8 NULL,
	hypervisor_read_io_bandwidth_max int8 NULL,
	hypervisor_read_io_bandwidth_avg int8 NULL,
	hypervisor_write_io_bandwidth_min int8 NULL,
	hypervisor_write_io_bandwidth_max int8 NULL,
	hypervisor_write_io_bandwidth_avg int8 NULL,
	cpu_usage_min int8 NULL,
	cpu_usage_max int8 NULL,
	cpu_usage_avg int8 NULL,
	memory_usage_min int8 NULL,
	memory_usage_max int8 NULL,
	memory_usage_avg int8 NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	used_storage int8 NULL,
	guest_os varchar NULL,
	power_usage numeric NULL
);