CREATE TABLE public.cluster_metrics (
	datacenter text NULL,
	"cluster" text NULL,
	"timestamp" timestamp NULL,
	vhost_count int4 NULL,
	vm_count int4 NULL,
	cpu_ghz_capacity numeric(10, 2) NULL,
	cpu_ghz_used numeric(10, 2) NULL,
	cpu_ghz_free numeric(10, 2) NULL,
	memory_capacity_gb numeric(10, 2) NULL,
	memory_used_gb numeric(10, 2) NULL,
	memory_free_gb numeric(10, 2) NULL,
	disk_usage_avg_kbps numeric(15, 2) NULL,
	disk_usage_min_kbps numeric(15) NULL,
	disk_usage_max_kbps numeric(15) NULL,
	network_usage_avg_kbps numeric(15, 2) NULL,
	network_usage_min_kbps numeric(15) NULL,
	network_usage_max_kbps numeric(15) NULL,
	memory_usage_avg_perc numeric(7, 2) NULL,
	memory_usage_min_perc numeric(7, 2) NULL,
	memory_usage_max_perc numeric(7, 2) NULL,
	cpu_usage_avg_perc numeric(7, 2) NULL,
	cpu_usage_min_perc numeric(7, 2) NULL,
	cpu_usage_max_perc numeric(7, 2) NULL,
	total_freespace_gb numeric(20, 2) NULL,
	total_capacity_gb numeric(20, 2) NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL
);

CREATE TABLE public.datacenter_metrics (
	datacenter text NULL,
	"timestamp" timestamp NULL,
	total_memory_capacity_gb numeric(10, 2) NULL,
	total_memory_used_gb numeric(10, 2) NULL,
	total_storage_capacity_gb numeric(20, 4) NULL,
	total_used_storage_gb numeric(20, 4) NULL,
	total_cpu_ghz_capacity numeric(10, 2) NULL,
	total_cpu_ghz_used numeric(10, 2) NULL,
	disk_usage_avg_kbps numeric(15, 2) NULL,
	disk_usage_min_kbps numeric(15) NULL,
	disk_usage_max_kbps numeric(15) NULL,
	network_usage_avg_kbps numeric(15, 2) NULL,
	network_usage_min_kbps numeric(15) NULL,
	network_usage_max_kbps numeric(15) NULL,
	memory_usage_avg_perc numeric(7, 2) NULL,
	memory_usage_min_perc numeric(7, 2) NULL,
	memory_usage_max_perc numeric(7, 2) NULL,
	cpu_usage_avg_perc numeric(7, 2) NULL,
	cpu_usage_min_perc numeric(7, 2) NULL,
	cpu_usage_max_perc numeric(7, 2) NULL,
	total_host_count int4 NULL,
	total_vm_count int4 NULL,
	total_cluster_count int4 NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL
);


CREATE TABLE public.vm_metrics (
	datacenter text NULL,
	"cluster" text NULL,
	vmhost text NULL,
	vmname text NOT NULL,
	"timestamp" timestamp NOT NULL,
	number_of_cpus int4 NULL,
	cpu_usage_avg_mhz numeric(10, 2) NULL,
	cpu_usage_min_mhz numeric(10, 2) NULL,
	cpu_usage_max_mhz numeric(10, 2) NULL,
	memory_usage_avg_perc numeric(5, 2) NULL,
	memory_usage_min_perc numeric(5, 2) NULL,
	memory_usage_max_perc numeric(5, 2) NULL,
	disk_usage_avg_kbps numeric(10, 2) NULL,
	disk_usage_min_kbps numeric(10, 2) NULL,
	disk_usage_max_kbps numeric(10, 2) NULL,
	guest_os text NULL,
	datastore text NULL,
	used_space_gb numeric(10, 2) NULL,
	provisioned_space_gb numeric(10, 2) NULL,
	folder text NULL,
	"uuid" text NOT NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	total_cpu_capacity_mhz numeric(20, 4) NULL,
	total_memory_capacity_gb numeric(20, 4) NULL,
	esxi_system_uuid varchar(36) NULL,
	boottime varchar(255) NULL
);


CREATE TABLE public.vmhost_metrics (
	datacenter text NULL,
	"cluster" text NULL,
	vmhost text NULL,
	"timestamp" timestamp NULL,
	esxi_system_uuid text NULL,
	esxi_bios_uuid text NULL,
	cpu_ghz_capacity numeric(10, 2) NULL,
	cpu_ghz_used numeric(10, 2) NULL,
	cpu_ghz_free numeric(10, 2) NULL,
	memory_capacity_gb numeric(10, 2) NULL,
	memory_used_gb numeric(10, 2) NULL,
	memory_free_gb numeric(10, 2) NULL,
	disk_usage_avg_kbps numeric(15, 2) NULL,
	disk_usage_min_kbps numeric(15) NULL,
	disk_usage_max_kbps numeric(15) NULL,
	network_usage_avg_kbps numeric(15, 2) NULL,
	network_usage_min_kbps numeric(15) NULL,
	network_usage_max_kbps numeric(15) NULL,
	memory_usage_avg_perc numeric(7, 2) NULL,
	memory_usage_min_perc numeric(7, 2) NULL,
	memory_usage_max_perc numeric(7, 2) NULL,
	cpu_usage_avg_perc numeric(7, 2) NULL,
	cpu_usage_min_perc numeric(7, 2) NULL,
	cpu_usage_max_perc numeric(7, 2) NULL,
	total_freespacegb numeric(20, 2) NULL,
	total_capacitygb numeric(20, 2) NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	power_usage numeric NULL,
	uptime varchar(255) NULL
);